version: '3.8'

services:
  todo-db:
    image: mysql:5.7
    container_name: todo-db
    networks:
      - todo-net
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    volumes:
      - ./todo_list.sql:/docker-entrypoint-initdb.d/init.sql

  todopy:
    build: .
    container_name: todopy
    networks:
      - todo-net
    ports:
      - "8888:8888"
    environment:
      DB_HOST: todo-db
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password

networks:
  todo-net:
